/* eslint-disable @next/next/no-page-custom-font */
/* eslint-disable @next/next/link-passhref */
import axios from 'axios'
import Head from 'next/head'
import { useEffect, useState } from 'react'
import Feature from '../components/Feature'
import Header from '../components/Header'
import Recipes from '../components/Recipes'
import { useRecoilState } from 'recoil'
import { modalState } from '../atoms/modalAtoms'
import RecipeDetails from '../components/RecipeDetails'


export default function Home() {
  const [feature, setFeature] = useState({})
  const [open, setOpen] = useRecoilState(modalState)
  const [ searchRecipe, setSearchRecipe ] = useState('')
  const [ viewRecipe, setViewRecipe ] = useState()
  const [ recipeDetails, setRecipeDetails ] = useState('')

  useEffect(() =>{
    const getFeature = async () => {
      const resp = await axios.get('https://www.themealdb.com/api/json/v1/1/random.php')

      setFeature(resp.data.meals[0])
      console.log(resp.data.meals[0])
    }

    return getFeature()

  }, [])

  useEffect(() => {

    if (viewRecipe){

      const getRecipe = async () => {
        const resp = await axios.get(`https://www.themealdb.com/api/json/v1/1/lookup.php?i=${viewRecipe}`)
  
        console.log(resp.data.meals[0])
        setRecipeDetails(resp.data.meals[0])
      }
      
      return getRecipe()

    }

  }, [viewRecipe])

  function handleSearchChange(e){
    setSearchRecipe(e.target.value)
    
  }

  const openModal = (recipe) => {
    setOpen(true)
    setViewRecipe(recipe)
    console.log(recipe)
  }

  return (
    <div className='bg-red-200 max-h-fit min-h-screen'>
      <Head>
        <title>Recipe Snips</title>
        <meta name="description" content="Generated by create next app" />
        
        <link rel="preconnect" href="https://fonts.googleapis.com" />
        <link rel="preconnect" href="https://fonts.gstatic.com" crossOrigin />
        <link href="https://fonts.googleapis.com/css2?family=Nunito&display=swap" rel="stylesheet" />
      </Head>
      <div className='w-10/12 mx-auto'>
        <Header
          onSearchChange={handleSearchChange}
        />
        
        <Feature
          feature={feature}
          onOpen={openModal}
        />
        <Recipes 
          searchRecipe={searchRecipe}
          onOpen={openModal}
        />
        <RecipeDetails 
          recipe={recipeDetails}
        />
      </div>
      
    </div>
  )
}
